### ISSUE TITLE
Env log parsing error in water units

### ISSUE THREAD

**Issue by jkuusk** [HYPERNETS/libhypstar#2]
https://github.com/HYPERNETS/libhypstar/blob/af79fe29bf639a5156dccc5daad87234a16d27e5/python/data_structs/environment_log.py#L93

If SWIR module is missing and temp is -999, then python complains:
Error : must be real number, not str.

See also
https://github.com/HYPERNETS/hypernets_tools/issues/24#issuecomment-783468655

**Comment by javierconcha** [comment]
@corizzi, @stiebrs How can I solve this issue? We are not able to take any measurement now and the deployment date is approaching fast. Thanks!

**Comment by stiebrs** [comment]
At the moment I don't have access to my development setup, as a workaround try commenting out lines 93 and 94
self.swir_body_temperature = self.swir_body_temperature if self.swir_body_temperature > -40 else 'N/A'
In 
hypernets/scripts/libhypstar/python/data_structs/environment_log.py 

Swir body and sink temperatures should then show up as - 999'C, which should be fine, since there are no sensors attached. 

I'll fix it in release when i get back


On February 23, 2021 10:17:20 AM UTC, "Javier A. Concha" <notifications@github.com> wrote:
>@corizzi, @stiebrs How can I solve this issue? We are not able to take
>any measurement now and the deployment date is approaching fast.
>Thanks!
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/HYPERNETS/libhypstar/issues/2#issuecomment-784079176

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by javierconcha** [comment]
I confirm the issue was solved following this:

> At the moment I don't have access to my development setup, as a workaround try commenting out lines 93 and 94 self.swir_body_temperature = self.swir_body_temperature if self.swir_body_temperature > -40 else 'N/A' In hypernets/scripts/libhypstar/python/data_structs/environment_log.py Swir body and sink temperatures should then show up as - 999'C, which should be fine, since there are no sensors attached. I'll fix it in release when i get back
> […](#)
> On February 23, 2021 10:17:20 AM UTC, "Javier A. Concha" ***@***.***> wrote: @corizzi, @stiebrs How can I solve this issue? We are not able to take any measurement now and the deployment date is approaching fast. Thanks! -- You are receiving this because you were mentioned. Reply to this email directly or view it on GitHub: [#2 (comment)](https://github.com/HYPERNETS/libhypstar/issues/2#issuecomment-784079176)
> -- Sent from my Android device with K-9 Mail. Please excuse my brevity.

The instrument is taking measurements now!
